name: Pull request
on: [pull_request]
jobs:
  some-job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a pull request."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server!"
      - run: echo "ğŸ” The name of the branch is ${{ github.ref }}." 
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test the code on the runner."
      - run: npm install
      - run: npm run build